server:
  port: 8090

spring:
  application:
    name: msvc-gestionDeUsuarios
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestionDeUsuariosDB
    username: root
    password: root
  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create
      database: mysql
      database-plataform: org.hibernate.dialect.MYSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
